dist: trusty
language: java
# We now cache the Maven dependencies directory for faster builds
cache:
  directories:
  - $HOME/.m2
sudo: true

before_install:
- echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc

matrix:
  fast_finish: true
  include:
  # checkstyle
  - jdk: oraclejdk11
    env:
    - DESC="checkstyle"
    - CMD="mvn clean checkstyle:check"
  # unit tests (oraclejdk11)
  - jdk: oraclejdk11
    env:
    - DESC="oraclejdk11 unit tests"
    - CMD="mvn clean test -Dcheckstyle.skip=true"
  # unit tests (openjdk11)
  - jdk: openjdk11
    env:
    - DESC="openjdk11 unit tests"
    - CMD="mvn clean test -Dcheckstyle.skip=true"
    - LANG=en_US.utf8

script: echo ${CMD}; ${CMD}
